name: Data Push

on:
  push:
    branches:
      - 'main'


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./data
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 23.x
    
    - name: NPM Install
      run: npm install

    - name: Crunch Excel Sheet
      run: npm run crunch
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out